# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMKObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект БМК',
                'verbose_name_plural': 'Объекты БМК',
            },
        ),
    ]
