# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-20 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribers', '0002_auto_20180215_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
